steps:
    - task: CopyFiles@2
      displayName: Copy output files
      inputs: 
          SourceFolder: $(Build.SourcesDirectory)
          TargetFolder: $(Build.ArtifactStagingDirectory)
          CleanTargetFolder: true

    - task: ArchiveFiles@2
      displayName: Archive files
      inputs:
        rootFolderOrFile: $(Build.ArtifactStagingDirectory)
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/mysb_forms-build_v$(Build.BuildNumber).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/mysb_forms-build_v$(Build.BuildNumber).zip
      artifact: drop
      displayName: Publish Artifact